### ISSUE TITLE
dunder attribute __repo__ of DataModel should start with "https:" instead of "git:"

### ISSUE THREAD

**Issue by haeussma** [JR-1991/software-driven-rdm#13]
When reading in a serialized instance of a DataModel (e.g. .yaml) by using
```python
path = "path_to_serialized_datamodel.yaml"
dataset, lib = sdRDM.DataModel.parse(path=path)
```
the lib cannot be created since ```__repo__``` in ```__source__```contains the right url, which starts with "git:" instead of "https:".

Solution:
```__repo__``` url should start with "https:"

**Comment by JR-1991** [comment]
Fixed by #14
