### ISSUE TITLE
Suggestion: Change use of [##] to section heading

### ISSUE THREAD

**Issue by torogi94** [JR-1991/software-driven-rdm#2]
Data models can get quite large. It could be interesting to be able to use second-level headings `##` in markdown for creating sections within the document to sort classes thematically, instead of using them for denoting the beginning of a class definition like third-level headings `###`.

**Comment by JR-1991** [comment]
That's a great idea! It may also benefit to the table of contents available at the GitHub Markdown preview.

You can also add multiple markdown files to the specifications directory if the data model is large. At generation, all of them will be merged into a single one.
