### ISSUE TITLE
Lowest level elements in XML cannot have attributes and content

### ISSUE THREAD

**Issue by torogi94** [JR-1991/software-driven-rdm#20]
Currently, when serialising a data model zu XML, it is not possible for the lowest level (most nested) elements to have any attributes when they are also supposed to hold content:

### Parent

- xml_element_that_should_hold_content
  - Type: string
  - Description: foobar
  - XML: elementWithContent

```XML
<parent>
    <elementWithContent>I need some string in here.</elementWithContent>
</parent>
```

There is no way to give any attributes to ```<elementWithContent/>```. However, if it should instead have no content and only attributes, that would not be a problem:

### Parent

- xml_element_without_content
  - Type: Element
  - Description: foobar
  - XML: elementWithoutContent
  
### Element
- an_attribute
  - Type: string
  - Description: foobar
  - XML: @anAttribute
- another_attribute
  - Type: int
  - Description: foobar
  - XML: @anotherAttribute

```XML
<parent>
    <elementWithoutContent anAttribute="abc" anotherAttribute=123/>
</parent>
```

Elements that both hold content themselves and have attributes are needed for various XML standards and should be supported!

**Comment by torogi94** [comment]
Sounds perfect! If that does not interfere with the concept as a whole or with serialisation to other formats like JSON then i find that to be a very good solution!

**Comment by JR-1991** [comment]
Got a first proposal #21! Could you check out the PR branch and test it too with the given examples?
