### ISSUE TITLE
Error: Pydantic ```email-validator``` is not installed

### ISSUE THREAD

**Issue by torogi94** [JR-1991/software-driven-rdm#22]
```- Type: Email``` currently produces an ```ImportError``` due to missing Pydantic ```email-validator``` dependency:

```
ImportError: email-validator is not installed, run `pip install pydantic[email]`
```

**Comment by JR-1991** [comment]
Please refer to PR #25 for a fix. You may test it by checking out the PRs branch and confirm the merge.
