### ISSUE TITLE
Implement setter method for attributes, that are not not multiples

### ISSUE THREAD

**Issue by haeussma** [JR-1991/software-driven-rdm#27]
Should work similar to the setter method of list attributes.

**Comment by JR-1991** [comment]
Instead of having a dedicated setter, add the sub object already but in a non instance state. 

Something like:

'''python
dataset.sub_object(
    name = "something"
)
'''

This may reduce boilerplate methods. Yet the setters would then be required for multi-typed attributes.

**Comment by JR-1991** [comment]
This has been added in commit https://github.com/JR-1991/software-driven-rdm/commit/92fcba2879f49c11f24be3c7b3d9123b883248bf and introduces it for sub-objects that do not contain `required` fields and has a single type. It behaves as follows:

```python
dataset = Container()
dataset.test.foo = "Hello"
dataset.test.bar = 100
```

which is equivalent to

```python
dataset = Container()
dataset.test = dataset.__types__.test(foo="Hello", bar=100)
```

If neither of both cases applies, every object possesses the `__types__` attribute from which the underlying objects can be drawn from.
