### ISSUE TITLE
GitHub action to generate API fails due to wrong imports

### ISSUE THREAD

**Issue by haeussma** [JR-1991/software-driven-rdm#34]
#  Description

Using the Github action to generate a Python API based on the markdown specifications fails, due to a wrong import.
Generating the API by calling ```generate_python_api()``` works as expected.

[See failed Action](https://github.com/FAIRChemistry/CaliPytion/actions/runs/5456511043/jobs/9929412389)

# Issue
Might only result from the recent Pydantic update to v.2. Some classes were renamed or are not supported anymore.

**Comment by JR-1991** [comment]
I added PR #35 to solve this in the long term. There are a lot of changes that need careful refactoring of the code base. For now, we'd require `pydantic <= 1.10.11` to keep the functionality
