### ISSUE TITLE
Empty sub-objects get same UUID

### ISSUE THREAD

**Issue by haeussma** [JR-1991/software-driven-rdm#46]
If a data model has sub-objects that may or may not be instantiated, empty sub-objects get the identical UUID.
![Screenshot 2023-11-27 at 10 18 42](https://github.com/JR-1991/software-driven-rdm/assets/83341109/402f9586-5fdc-410f-84ff-fcec7b26cf79)

**Comment by JR-1991** [comment]
Was able to fix the issue. Can you test on your end again to confirm?

<img width="1840" alt="image" src="https://github.com/JR-1991/software-driven-rdm/assets/30547301/94727a3e-11b5-4eb5-a158-1610b7563fe5">

**Comment by haeussma** [comment]
Yes, issue is fixed!
