### ISSUE TITLE
Dimensionslose Werte

### ISSUE THREAD

**Issue by lucapattas** [JR-1991/software-driven-rdm#56]
Wenn ich `unit` einen leeren String übergebe wird daraus ein NoneType und ich ich bekommen einen ValidationError, da NoneType nicht vom Typ Unit ist. `unit="1"` funktioniert, wodurch aber `Unit(name='', bases=[])` resultiert. Ich fände es hilfreich durch `unit=""` bzw. `unit="1"` dimensionslose Größen als solche zu kennzeichnen, die später auch mit anderen (skalierten) AstroPy Quantities verrechenbar sind (siehe https://docs.astropy.org/en/stable/units/standard_units.html#the-dimensionless-unit).

**Comment by JR-1991** [comment]
@lucapattas thanks for submitting the issue! Switching to english for other users to be able to get into it too. Indeed, this seems to break the `Unit` class. Will create a pull request to address this asap.

**Comment by JR-1991** [comment]
@lucapattas can you please check the PR I have submitted?

**Comment by lucapattas** [comment]
Thanks!
